version: '3.8'

services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: api_users_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - "DATABASE_URL=mysql://root:root@mysql:3306/symfony?serverVersion=8.0"
    networks:
      - app
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: api_users_nginx
    restart: always
    ports:
      - "80:8080"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: api_users_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data-app:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql_data-app:
    driver: local